services:
  lesson_schedule_parser:
    restart: always
    build: ./
    container_name: lesson_schedule_parser
    volumes:
      - data:/app/data
      - ./.env/:/app/.env:ro
    environment:
      - TZ=Asia/Yerevan

volumes:
  data: