name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: "string"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - run: npm i
    - run: npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build
          .gitignore
          package.json
          package-lock.json
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/build.zip"
        tag: "${{ github.event.inputs.tag }}"
